on:
  push:
    branches:
    - main
jobs:
  gradle:
    name: 构建项目
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: 配置java环境
      uses: actions/setup-java@v3.14.1
      with:
        java-version: 21
        distribution: temurin
    - name: 设置gradle
      uses: gradle/actions/setup-gradle@v4.4.1
    - name: 编译
      run: ./gradlew build
    - name: 上传fabric构建
      uses: actions/upload-artifact@v4
      with:
        name: fabric
        path: ./fabric/build/libs/*.jar
    - name: 上传forge构建
      uses: actions/upload-artifact@v4
      with:
        name: forge
        path: ./neoforge/build/libs/*.jar
